name: Test Runner
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted   # ðŸ‘ˆ this means it runs on your Ubuntu runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display system info
        run: |
          echo "âœ… Running on self-hosted Ubuntu runner"
          uname -a
          df -h
          whoami
